const dummyTweets = [
  "Just finished a long day at work and ready for some relaxation time 🛀💆‍♀️ #selfcare #relaxation #worklifebalance",
  "Just finished a long day at work and ready for some relaxation time 🛀💆‍♀️ #selfcare #relaxation #worklifebalance",
  "Excited to try out this new recipe I found online! 🍝👩‍🍳 #cooking #foodie #newrecipe",
  "Can't wait for the weekend to start! 😎🎉 #weekendvibes #friyay #excited",
  "Just started a new book and already hooked! 📚🤓 #reading #bookworm #newbook",
  "Feeling grateful for my amazing friends and family today ❤️👨‍👩‍👧‍👦 #grateful #family #friends",
  "Just got back from a great workout at the gym 💪🏋️‍♀️ #fitness #workout #gym",
  "Loving this new song that just came out! 🎶🎵 #music #newrelease #goodvibes",
  "Can't believe how fast time is flying by this year! ⏰📅 #timemovesfast #2023 #timeflies",
  "Excited to see my favorite band in concert next month! 🎤🎸 #concert #musiclover #excited",
  "Feeling inspired after attending a great conference today 🤩👩‍💼 #conference #inspired #networking",
  "Just tried a new coffee shop and it was amazing ☕️😍 #coffee #coffeelover #newplace",
  "Loving the warm weather lately ☀️🌡️ #springtime #warmweather #sunnydays",
  "Can't wait to travel and explore new places once it's safe to do so ✈️🌍 #travel #adventure #explore",
  "Feeling proud of myself for accomplishing a difficult task at work today 🏆👏 #achievement #work #success",
  "Just finished a great yoga class and feeling so relaxed 🧘‍♀️🙏 #yoga #relaxation #mindfulness",
  "Can't believe how quickly my little nephew is growing up! 👶👦 #family #growingup #timeflies",
  "Loving this new art exhibit I visited today 🎨🖼️ #art #museum #culture",
  "Excited to see my favorite team play in the championship game tomorrow! 🏀🥇 #basketball #championship #teamspirit",
  "Just learned a new skill and feeling accomplished 💪👨‍🎓 #learning #skillbuilding #personaldevelopment",
  "Feeling grateful for the simple pleasures in life today 💕🌸 #grateful #happiness #blessed",
  "Just got back from an amazing vacation and feeling refreshed ✈️🏖️ #vacation #travel #relaxation",
  "Loving this new fashion trend I've been seeing everywhere 👗👠 #fashion #style #trendy",
  "Can't wait to try out this new restaurant that just opened up! 🍽️🍴 #foodie #newplace #restaurant",
  "Feeling motivated and ready to tackle the day 💪🌟 #motivation #productivity #mindset",
  "Just finished a great workout with my personal trainer 💪🏋️‍♂️ #fitness #personaltraining #gains",
  "Can't believe it's already March! Where did the time go? ⏰📆 #timemovesfast #March #newmonth",
  "Loving my new haircut! 💇‍♀️👌 #hairstyle #freshlook #haircut",
  "Excited for the weekend ahead and all the fun activities planned 🎉🤩 #weekendfun #activities #excited",
  "Just finished a great book and feeling satisfied 📚😌 #reading #booklover #satisfied",
  "Feeling grateful for my health and the ability to stay active 💪🙏 #health #fitness #grateful",
  "Can't wait to see the new movie that just came out! 🍿🎥 #movie #newrelease #excited",
  "Loving the beautiful nature surrounding me on my morning walk 🌳🌿 #nature #walking #peaceful",
  "Feeling proud of myself for accomplishing a personal goal today 🎉🙌 #achievement #personaldevelopment #success",
  "Just tried a new workout class and it was amazing! 🏋️‍♀️💪 #fitness #workout #newclass",
  "Excited for the start of a new week and all the possibilities it holds 🌟👩‍💼 #MondayMotivation #newweek #positivity",
  "Feeling inspired after attending an empowering women's event today 💪👩‍🎤 #empowerment #women #inspired",
  "Just had a great conversation with an old friend and feeling happy ☎️❤️ #friendship #conversation #happy",
  "Can't wait to start planning my next vacation! 🌍✈️ #travel #vacation #planning",
  "Loving this new hobby I picked up and the creative outlet it provides 🎨🖌️ #hobby #creativity #art",
  "Feeling grateful for the support and love from my family and friends ❤️👨‍👩‍👧‍👦 #grateful #support #love",
  "Just finished a great movie and feeling emotional 🎥😭 #movie #emotional #tearjerker",
  "Excited to attend a live concert tonight and see my favorite artist perform 🎶🎤 #concert #music #excited",
  "Loving the new workout routine I started and already seeing results 💪🏋️‍♂️ #fitness #workout #results",
  "Can't wait to try out this new recipe I found on Pinterest! 🍴👩‍🍳 #cooking #foodie #newrecipe",
  "Feeling motivated and determined to achieve my goals 💪🌟 #motivation #goals #determination",
  "Just finished a great book club meeting and feeling fulfilled 📚👥 #bookclub #reading #fulfilled",
  "Can't believe it's already been a year since my last vacation 😱🏖️ #timeflies #vacation #memories",
  "Loving the new clothing line from my favorite designer 👗👠 #fashion #style #designer",
  "Excited to start a new chapter in my life and see where it takes me 🌟📖 #newbeginnings #lifechanges #excited",
  "Feeling grateful for the simple things in life like a warm cup of tea ☕️🙏 #gratitude #simplicity #happiness",
  "Just tried a new restaurant and the food was amazing! 🍽️👌 #foodie #restaurant #delicious",
  "Can't wait for the weekend and some much-needed relaxation time 🧘‍♀️🌴 #weekendvibes #relaxation #selfcare",
  "Loving the new music playlist I made and the energy it brings 🎶🔥 #music #playlist #energy",
  "Feeling inspired after attending a motivational speaker event 🌟💪 #motivation #inspiration #empowerment",
  "Just finished a challenging workout and feeling proud 💪🏋️‍♀️ #fitness #workout #proud",
  "Excited to start a new project at work and make a positive impact 👩‍💻🌟 #work #project #impact",
  "Loving the beautiful sunset tonight and feeling grateful for nature 🌅🌿 #sunset #nature #gratitude",
  "Feeling accomplished after completing a long to-do list today 📝✅ #productivity #accomplishment #success",
  "Just had a great time catching up with an old friend over coffee ☕️❤️ #friendship #coffee #conversation",
  "Can't wait for the next season of my favorite TV show to start 📺🍿 #TVshow #excited #entertainment",
  "Loving the new skincare routine I started and already noticing a difference 🧖‍♀️🌟 #skincare #beauty #routine",
  "Feeling grateful for the love and support of my significant other ❤️👫 #love #relationshipgoals #support",
  "Just tried a new workout supplement and feeling energized 💪🏋️‍♂️ #fitness #supplements #energy",
  "Excited to start planning for the upcoming holiday season 🎄🎁 #holidays #planning #festive",
  "Loving the new book I'm reading and the escape it provides 📚🌟 #reading #escape #books",
  "Feeling inspired after attending a TED talk event today 🌟💡 #inspiration #TEDtalks #empowerment",
  "Just finished a great yoga class and feeling centered 🧘‍♀️🙏 #yoga #meditation #centered",
  "Can't wait to see the new exhibit at the art museum 🎨🖼️ #art #museum #exhibit",
  "Loving the new outdoor hobby I picked up and the connection with nature it brings 🌲🌿 #outdoors #hobby #nature",
  "Feeling grateful for the supportive and positive people in my life ❤️👥 #grateful #support #positivity",
  "Just finished a great volunteer event and feeling fulfilled 🙌🌟 #volunteering #community #fulfilled",
  "Excited to start planning my next adventure and travel to new places 🌍✈️ #travel #adventure #exploration",
  "Loving the new home decor I just purchased and the cozy atmosphere it creates 🏡🌟 #homedecor #cozy #atmos phere",
  "Feeling accomplished after completing a challenging project at work 💼👊 #work #project #success",
  "Just had a great workout session with my workout buddy 💪👯‍♀️ #fitness #workout #motivation",
  "Can't wait to try the new restaurant that just opened in town 🍴🌟 #restaurant #foodie #excited",
  "Loving the new outfit I just bought and feeling confident 💃👗 #fashion #confidence #newoutfit",
  "Feeling grateful for the little moments of joy in life like watching the sunset 🌅🙏 #gratitude #joy #simplepleasures",
  "Just finished a great hike and feeling energized 🚶‍♀️🌿 #hiking #nature #energized",
  "Excited to start learning a new language and broaden my horizons 🌎🗣️ #languagelearning #education #expandingmyhorizons",
  "Loving the new podcast I started listening to and the new perspectives it brings 🎧🌟 #podcast #perspective #inspiration",
  "Feeling inspired after attending a workshop on entrepreneurship 🌟💡 #entrepreneurship #inspiration #empowerment",
  "Just had a great date night with my significant other and feeling loved ❤️👫 #datenight #love #romance",
  "Can't wait to see the new movie that just came out in theaters 🎥🍿 #movies #entertainment #excited",
  "Loving the new workout routine I started and feeling stronger 💪🏋️‍♂️ #fitness #workout #strength",
  "Feeling grateful for the support and encouragement of my family 🙏❤️ #family #support #gratitude",
  "Just finished a great book and feeling inspired 📖🌟 #reading #inspiration #books",
  "Excited to start a new hobby and explore my creative side 🎨🌟 #hobby #creativity #exploration",
  "Loving the new recipe I tried and the delicious meal it created 🍴🌟 #cooking #foodie #delicious",
  "Feeling accomplished after completing a difficult task 💪👊 #accomplishment #success #hardwork",
  "Just had a great workout at the gym and feeling proud 💪🏋️‍♀️ #fitness #workout #proud",
  "Can't wait to attend the concert of my favorite musician 🎶🎤 #concert #music #excited",
  "Loving the new hairstyle I got and feeling confident 💇💁 #hairstyle #confidence #newlook",
  "Feeling grateful for the beauty of nature and the peace it brings 🌿🙏 #nature #beauty #peace",
  "Just finished a great run outside and feeling invigorated 🏃‍♀️🌅 #running #outdoors #energized",
  "Excited to start planning my next vacation and explore a new destination 🌴✈️ #travel #vacation #exploration",
  "Loving the new skill I learned and feeling accomplished 🌟👊 #learning #skillbuilding #accomplishment",
  "Feeling inspired after attending a live music performance 🎶🌟 #music #inspiration #liveperformance",
  "Just had a great conversation with a friend and feeling grateful for their support 🙏❤️ #friendship #support #gratitude",
  "Can't wait to start a new project and see where it takes me 🌟💡 #project #creativity #excited",
];

const dummyUser = [
  {
    _id: "63fda68a996f42a70801c5fb",
    name: "Dev Kahar",
    email: "dev@gmail.com",
  },
  {
    _id: "63fdc99f520d2d407d3052f6",
    name: "Roch Borrows",
    email: "rborrows0@mayoclinic.com",
  },
  {
    _id: "63fdc99f520d2d407d3052f7",
    name: "Alwin Pitt",
    email: "apitt1@theatlantic.com",
  },
  {
    _id: "63fdc99f520d2d407d3052f8",
    name: "Gunter Millward",
    email: "gmillward2@java.com",
  },
  {
    _id: "63fdc99f520d2d407d3052f9",
    name: "Angele Senter",
    email: "asenter3@telegraph.co.uk",
  },
  {
    _id: "63fdc99f520d2d407d3052fa",
    name: "Halie Hollows",
    email: "hhollows4@ca.gov",
  },
  {
    _id: "63fdc99f520d2d407d3052fb",
    name: "Chickie Brend",
    email: "cbrend5@linkedin.com",
  },
  {
    _id: "63fdc99f520d2d407d3052fc",
    name: "Leda Cregeen",
    email: "lcregeen6@netscape.com",
  },
  {
    _id: "63fdc99f520d2d407d3052fd",
    name: "Dewie Milier",
    email: "dmilier7@latimes.com",
  },
  {
    _id: "63fdc99f520d2d407d3052fe",
    name: "Camey McPake",
    email: "cmcpake8@ezinearticles.com",
  },
  {
    _id: "63fdc99f520d2d407d3052ff",
    name: "Carri Jerrolt",
    email: "cjerrolt9@ask.com",
  },
];

module.exports = {
  dummyTweets,
  dummyUser,
};
